services:
  - type: web
    name: contact-web
    env: ruby
    buildCommand: bundle install && bundle exec rake assets:precompile db:migrate
    startCommand: bundle exec puma -C config/puma.rb
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: contact-db
          property: connectionString
      - key: REDIS_URL
        value: rediss://default:AWgrAAIjcDEzMDc2ZDVjNTgxODQ0YzkxOTgyZDdjNmIxY2IyNjkwY3AxMA@certain-roughy-26667.upstash.io:6379
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: cf797dcf5a49c0183358328cdd3958c2

  - type: worker
    name: contact-sidekiq
    env: ruby
    buildCommand: bundle install
    startCommand: bundle exec sidekiq
    envVars:
      - fromService:
          name: contact-web
          key: DATABASE_URL
      - key: REDIS_URL
        value: rediss://default:AWgrAAIjcDEzMDc2ZDVjNTgxODQ0YzkxOTgyZDdjNmIxY2IyNjkwY3AxMA@certain-roughy-26667.upstash.io:6379
      - key: RAILS_ENV
        value: production
      - key: RAILS_MASTER_KEY
        value: cf797dcf5a49c0183358328cdd3958c2
